[[collection]]
type = "card_simple"
title = "Breakfast at Tiffany’s"
content = "Deep Blue Something"

[[collection]]
type = "card_simple"
title = "Sunshine of Your Love (Simplified)"
content = "Eric Claption"

[[collection]]
type = "card_simple"
title = "Surfin’ USA"
content = "Beach Boys"

[[collection]]
type = "card_simple"
title = "Ain’t no Sunshine"
content = "Bill Withers"

[[collection]]
type = "card_simple"
title = "Jingle Bells"
content = ""

[[collection]]
type = "card_simple"
title = "Last Christmas"
content = "Wham!"

[[collection]]
type = "card_simple"
title = "Born in the USA"
content = "Bruce Springsteen"

[[collection]]
type = "card_simple"
title = "505"
content = "Arctic Monkeys"

[[collection]]
type = "card_simple"
title = "Heroes"
content = "David Bowie"

[[collection]]
type = "card_simple"
title = "Walk of Life"
content = "Dire Straits"

[[collection]]
type = "card_simple"
title = "Love Me Do"
content = "The Beatles"

[[collection]]
type = "card_simple"
title = "Wish You Were Here"
content = "Pink Floyd"

[[collection]]
type = "card_simple"
title = "Wonderwall"
content = "Oasis"

[[collection]]
type = "card_simple"
title = "Love Me Do"
content = "The Beatles"

[[collection]]
type = "card_simple"
title = "Sweet Home Alabama"
content = "Lynyrd Skynyrd"

[[collection]]
type = "card_simple"
title = "Boulevard of Broken Dreams"
content = "Green Day"
