[[collection]]
type = "card_simple"
title = "Dreams"
content = "Fleetwood Mac"

[[collection]]
type = "card_simple"
title = "Free Fallin’"
content = "Tom Petty"

[[collection]]
type = "card_simple"
title = "House of the Rising Sun"
content = "The Animals"

[[collection]]
type = "card_simple"
title = "Counting Stars"
content = "OneRepublic"

[[collection]]
type = "card_simple"
title = "Video Games"
content = "Lana Del Rey"

[[collection]]
type = "card_simple"
title = "Should I Stay or Should I Go"
content = "The Clash"

[[collection]]
type = "card_simple"
title = "Champagne Supernova"
content = "Oasis"

[[collection]]
type = "card_simple"
title = "Eleanor Rigby"
content = "The Beatles"

[[collection]]
type = "card_simple"
title = "Californication"
content = "RHCP"

[[collection]]
type = "card_simple"
title = "Anarchy in the UK"
content = "The Sex Pistols"

[[collection]]
type = "card_simple"
title = "Smells like Teen Spirit"
content = "Nirvana"

[[collection]]
type = "card_simple"
title = "Come as You Are"
content = "Nirvana"

[[collection]]
type = "card_simple"
title = "Wake Me Up"
content = "Avicii"

[[collection]]
type = "card_simple"
title = "Sweet Child o’ Mine"
content = "Guns N Roses"

[[collection]]
type = "card_simple"
title = "Let Her Go"
content = "Passenger"