[[collection]]
type = "card_simple"
title = "The Twilight of the American Enlightenment"
content = "George Mardsen"

[[collection]]
type = "card_simple"
title = "The Life and Times of the Thunderbolt Kid"
content = "Bill Bryson"

[[collection]]
type = "card_simple"
title = "Chinese Machiavelli: 5,000 Years of Chinese Statecraft"
content = "Dennis Bloodworth & Ching-pei Bloodworth"

[[collection]]
type = "card_simple"
title = "Mountain of Fame: Portraits in Chinese History"
content = "John E. Willis"

[[collection]]
type = "card_simple"
title = "Readings in Classical Chinese Philosophy"
content = "Philip Ivanhoe & Bryan van Norden"

[[collection]]
type = "card_simple"
title = " The Philosophy of the Dao De Jing"
content = "Hans Georg Moller"


[[collection]]
type = "card_simple"
title = "Finding Them Gone: Visiting the Poets of Chinaâ€™s Past"
content = "Bill Porter"

[[collection]]
type = "card_simple"
title = "The Shaolin Monastery"
content = "Meir Shahar"


[[collection]]
type = "card_simple"
title = "Sex, Drugs and Cocoa Puffs"
content = "Chuck Klosterman"